Fix the path to the state directory

diff --git a/.chezmoiscripts/run_onchange_after_migrate-to-state-directory b/.chezmoiscripts/run_onchange_after_migrate-to-state-directory
--- a/.chezmoiscripts/run_onchange_after_migrate-to-state-directory
+++ b/.chezmoiscripts/run_onchange_after_migrate-to-state-directory
@@ -1,24 +1,23 @@
 #!/bin/sh
 
-# Note: “local” and “mktemp” are non-POSIX.
+# Note: “local” is non-POSIX.
 
 set -o errexit -o nounset
 
 move_or_concatenate() {
-	local cache=~/.cache/"$1" state=~/.state/"$1" swap
+	local state=~/.local/state/"$1" src from
 
-	if ! [ -f "${cache}" ]
-	then >&2 echo "[info] already migrated: $1"
-	elif [ -f "${state}" ]
-	then
-		# need to merge the two files
-		swap="$(mktemp)"
-		>&2 echo "[info] temporary file created: ${swap}"
-		cat "${cache}" "${state}" >"${swap}"
-		mv -v "${swap}" "${state}"
-		rm -v "${swap}"
-	else mv -v "${cache}" "${state}"
-	fi
+	for src in .cache .state
+	do
+		from=~/"$src/$1"
+		if ! [ -f "$from" ]
+		then >&2 echo "[info] already migrated: $from"
+		else
+			>&2 echo "[info] migrating: $from"
+			cat "$from" >>"$state"
+			rm "$from"
+		fi
+	done
 }
 
 move_or_concatenate irb/history
@@ -27,10 +26,13 @@ move_or_concatenate less/history
 move_or_concatenate nodejs/repl_history
 move_or_concatenate zsh/history
 
-vim_cache=~/.cache/vim/info vim_state=~/.state/vim/info
-if ! [ -f "${vim_cache}" ]
-then >&2 echo '[info] already migrated: Vim'
-elif [ -f "${vim_state}" ]
-then >&2 echo '[error] Vim file needs to be manually migrated!'; exit 1
-else mv -v "${vim_cache}" "${vim_state}"
-fi
+for src in .cache .state
+do
+	from=~/"$src"/vim/info vim_state=~/.local/state/vim/info
+	if ! [ -f "${from}" ]
+	then >&2 echo "[info] already migrated: $from"
+	elif [ -f "${vim_state}" ]
+	then >&2 echo '[error] Vim file needs to be manually migrated!'; exit 1
+	else mv -v "${from}" "${vim_state}"
+	fi
+done
